version: '3.1'
services:
  db:
    image: postgres:15beta1-bullseye
    container_name: pix_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pix_db
    ports:
      - 5432:5432